# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\data\development\apis\APIS3\APIS\ui\apis_image_selection_list_advanced_properties.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_apisImageSelectionListDialog(object):
    def setupUi(self, apisImageSelectionListDialog):
        apisImageSelectionListDialog.setObjectName("apisImageSelectionListDialog")
        apisImageSelectionListDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        apisImageSelectionListDialog.resize(1119, 635)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/APIS/icons/apis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        apisImageSelectionListDialog.setWindowIcon(icon)
        apisImageSelectionListDialog.setModal(True)
        self.horizontalLayout = QtWidgets.QHBoxLayout(apisImageSelectionListDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uiTablePropertiesSplitter = QtWidgets.QSplitter(apisImageSelectionListDialog)
        self.uiTablePropertiesSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.uiTablePropertiesSplitter.setObjectName("uiTablePropertiesSplitter")
        self.gridLayoutWidget = QtWidgets.QWidget(self.uiTablePropertiesSplitter)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uiResetSelectionBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.uiResetSelectionBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/APIS/icons/deselection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiResetSelectionBtn.setIcon(icon1)
        self.uiResetSelectionBtn.setAutoDefault(False)
        self.uiResetSelectionBtn.setObjectName("uiResetSelectionBtn")
        self.horizontalLayout_2.addWidget(self.uiResetSelectionBtn)
        self.uiImageTBtn = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/APIS/icons/images.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiImageTBtn.setIcon(icon2)
        self.uiImageTBtn.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.uiImageTBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.uiImageTBtn.setObjectName("uiImageTBtn")
        self.horizontalLayout_2.addWidget(self.uiImageTBtn)
        self.uiLayerTBtn = QtWidgets.QToolButton(self.gridLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/APIS/icons/layer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiLayerTBtn.setIcon(icon3)
        self.uiLayerTBtn.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.uiLayerTBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.uiLayerTBtn.setObjectName("uiLayerTBtn")
        self.horizontalLayout_2.addWidget(self.uiLayerTBtn)
        self.uiPdfExportTBtn = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPdfExportTBtn.sizePolicy().hasHeightForWidth())
        self.uiPdfExportTBtn.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plugins/APIS/icons/pdf_export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiPdfExportTBtn.setIcon(icon4)
        self.uiPdfExportTBtn.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.uiPdfExportTBtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.uiPdfExportTBtn.setObjectName("uiPdfExportTBtn")
        self.horizontalLayout_2.addWidget(self.uiPdfExportTBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.uiTogglePropertyPanelBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plugins/APIS/icons/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiTogglePropertyPanelBtn.setIcon(icon5)
        self.uiTogglePropertyPanelBtn.setCheckable(True)
        self.uiTogglePropertyPanelBtn.setChecked(True)
        self.uiTogglePropertyPanelBtn.setAutoDefault(False)
        self.uiTogglePropertyPanelBtn.setObjectName("uiTogglePropertyPanelBtn")
        self.horizontalLayout_2.addWidget(self.uiTogglePropertyPanelBtn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.uiImageCountLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uiImageCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiImageCountLbl.setObjectName("uiImageCountLbl")
        self.horizontalLayout_3.addWidget(self.uiImageCountLbl)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.uiImageFilterCountLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uiImageFilterCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiImageFilterCountLbl.setObjectName("uiImageFilterCountLbl")
        self.horizontalLayout_3.addWidget(self.uiImageFilterCountLbl)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.uiImageSelectedCountLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uiImageSelectedCountLbl.setObjectName("uiImageSelectedCountLbl")
        self.horizontalLayout_3.addWidget(self.uiImageSelectedCountLbl)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.uiScanCountLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uiScanCountLbl.setLineWidth(1)
        self.uiScanCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiScanCountLbl.setObjectName("uiScanCountLbl")
        self.horizontalLayout_3.addWidget(self.uiScanCountLbl)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.uiScanFilterCountLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uiScanFilterCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiScanFilterCountLbl.setObjectName("uiScanFilterCountLbl")
        self.horizontalLayout_3.addWidget(self.uiScanFilterCountLbl)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.uiScanSelectedCountLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uiScanSelectedCountLbl.setObjectName("uiScanSelectedCountLbl")
        self.horizontalLayout_3.addWidget(self.uiScanSelectedCountLbl)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.uiHiResCountLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uiHiResCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiHiResCountLbl.setObjectName("uiHiResCountLbl")
        self.horizontalLayout_3.addWidget(self.uiHiResCountLbl)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.uiHiResFilterCountLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uiHiResFilterCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiHiResFilterCountLbl.setObjectName("uiHiResFilterCountLbl")
        self.horizontalLayout_3.addWidget(self.uiHiResFilterCountLbl)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.uiHiResSelectedCountLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uiHiResSelectedCountLbl.setObjectName("uiHiResSelectedCountLbl")
        self.horizontalLayout_3.addWidget(self.uiHiResSelectedCountLbl)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.uiOrthoCountLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uiOrthoCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiOrthoCountLbl.setObjectName("uiOrthoCountLbl")
        self.horizontalLayout_3.addWidget(self.uiOrthoCountLbl)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.uiOrthoFilterCountLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uiOrthoFilterCountLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiOrthoFilterCountLbl.setObjectName("uiOrthoFilterCountLbl")
        self.horizontalLayout_3.addWidget(self.uiOrthoFilterCountLbl)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.uiOrthoSelectedCountLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uiOrthoSelectedCountLbl.setObjectName("uiOrthoSelectedCountLbl")
        self.horizontalLayout_3.addWidget(self.uiOrthoSelectedCountLbl)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.uiImageCountLabelLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.uiImageCountLabelLbl.setObjectName("uiImageCountLabelLbl")
        self.horizontalLayout_3.addWidget(self.uiImageCountLabelLbl)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.uiFilterGrp = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.uiFilterGrp.setCheckable(True)
        self.uiFilterGrp.setChecked(False)
        self.uiFilterGrp.setObjectName("uiFilterGrp")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.uiFilterGrp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.uiFilterVerticalChk = QtWidgets.QCheckBox(self.uiFilterGrp)
        self.uiFilterVerticalChk.setChecked(True)
        self.uiFilterVerticalChk.setObjectName("uiFilterVerticalChk")
        self.gridLayout_3.addWidget(self.uiFilterVerticalChk, 0, 0, 2, 1)
        self.uiFilterScaleOperatorCombo = QtWidgets.QComboBox(self.uiFilterGrp)
        self.uiFilterScaleOperatorCombo.setObjectName("uiFilterScaleOperatorCombo")
        self.uiFilterScaleOperatorCombo.addItem("")
        self.uiFilterScaleOperatorCombo.addItem("")
        self.uiFilterScaleOperatorCombo.addItem("")
        self.gridLayout_3.addWidget(self.uiFilterScaleOperatorCombo, 1, 3, 1, 1)
        self.uiFilterObliqueChk = QtWidgets.QCheckBox(self.uiFilterGrp)
        self.uiFilterObliqueChk.setChecked(True)
        self.uiFilterObliqueChk.setObjectName("uiFilterObliqueChk")
        self.gridLayout_3.addWidget(self.uiFilterObliqueChk, 0, 1, 2, 1)
        self.uiFilterScaleLbl = QtWidgets.QLabel(self.uiFilterGrp)
        self.uiFilterScaleLbl.setObjectName("uiFilterScaleLbl")
        self.gridLayout_3.addWidget(self.uiFilterScaleLbl, 0, 3, 1, 2)
        self.uiFilterFilmKindCombo = QtWidgets.QComboBox(self.uiFilterGrp)
        self.uiFilterFilmKindCombo.setObjectName("uiFilterFilmKindCombo")
        self.gridLayout_3.addWidget(self.uiFilterFilmKindCombo, 1, 6, 1, 1)
        self.uiFilterScanCombo = QtWidgets.QComboBox(self.uiFilterGrp)
        self.uiFilterScanCombo.setObjectName("uiFilterScanCombo")
        self.uiFilterScanCombo.addItem("")
        self.uiFilterScanCombo.addItem("")
        self.gridLayout_3.addWidget(self.uiFilterScanCombo, 1, 8, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 7, 2, 1)
        self.uiFilterScanChk = QtWidgets.QCheckBox(self.uiFilterGrp)
        self.uiFilterScanChk.setTristate(False)
        self.uiFilterScanChk.setObjectName("uiFilterScanChk")
        self.gridLayout_3.addWidget(self.uiFilterScanChk, 0, 8, 1, 1)
        self.uiFilterOrthoCombo = QtWidgets.QComboBox(self.uiFilterGrp)
        self.uiFilterOrthoCombo.setObjectName("uiFilterOrthoCombo")
        self.uiFilterOrthoCombo.addItem("")
        self.uiFilterOrthoCombo.addItem("")
        self.gridLayout_3.addWidget(self.uiFilterOrthoCombo, 1, 10, 1, 1)
        self.uiFilterOrthoChk = QtWidgets.QCheckBox(self.uiFilterGrp)
        self.uiFilterOrthoChk.setTristate(False)
        self.uiFilterOrthoChk.setObjectName("uiFilterOrthoChk")
        self.gridLayout_3.addWidget(self.uiFilterOrthoChk, 0, 10, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 5, 2, 1)
        self.uiFilterScaleEdit = QtWidgets.QLineEdit(self.uiFilterGrp)
        self.uiFilterScaleEdit.setObjectName("uiFilterScaleEdit")
        self.gridLayout_3.addWidget(self.uiFilterScaleEdit, 1, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 0, 2, 2, 1)
        self.uiFilterHiResCombo = QtWidgets.QComboBox(self.uiFilterGrp)
        self.uiFilterHiResCombo.setObjectName("uiFilterHiResCombo")
        self.uiFilterHiResCombo.addItem("")
        self.uiFilterHiResCombo.addItem("")
        self.gridLayout_3.addWidget(self.uiFilterHiResCombo, 1, 9, 1, 1)
        self.uiFilterFilmKindChk = QtWidgets.QCheckBox(self.uiFilterGrp)
        self.uiFilterFilmKindChk.setObjectName("uiFilterFilmKindChk")
        self.gridLayout_3.addWidget(self.uiFilterFilmKindChk, 0, 6, 1, 1)
        self.uiFilterHiResChk = QtWidgets.QCheckBox(self.uiFilterGrp)
        self.uiFilterHiResChk.setTristate(False)
        self.uiFilterHiResChk.setObjectName("uiFilterHiResChk")
        self.gridLayout_3.addWidget(self.uiFilterHiResChk, 0, 9, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 11, 2, 1)
        self.uiFilterToDate = QtWidgets.QDateEdit(self.uiFilterGrp)
        self.uiFilterToDate.setObjectName("uiFilterToDate")
        self.gridLayout_3.addWidget(self.uiFilterToDate, 1, 13, 1, 1)
        self.uiFilterFromDate = QtWidgets.QDateEdit(self.uiFilterGrp)
        self.uiFilterFromDate.setObjectName("uiFilterFromDate")
        self.gridLayout_3.addWidget(self.uiFilterFromDate, 0, 13, 1, 1)
        self.uiFilterFromChk = QtWidgets.QCheckBox(self.uiFilterGrp)
        self.uiFilterFromChk.setObjectName("uiFilterFromChk")
        self.gridLayout_3.addWidget(self.uiFilterFromChk, 0, 12, 1, 1)
        self.uiFilterToChk = QtWidgets.QCheckBox(self.uiFilterGrp)
        self.uiFilterToChk.setObjectName("uiFilterToChk")
        self.gridLayout_3.addWidget(self.uiFilterToChk, 1, 12, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout.addWidget(self.uiFilterGrp, 4, 0, 1, 1)
        self.uiImageListTableV = QtWidgets.QTableView(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiImageListTableV.sizePolicy().hasHeightForWidth())
        self.uiImageListTableV.setSizePolicy(sizePolicy)
        self.uiImageListTableV.setSortingEnabled(True)
        self.uiImageListTableV.setObjectName("uiImageListTableV")
        self.gridLayout.addWidget(self.uiImageListTableV, 2, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.uiTablePropertiesSplitter)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.uiImageNumberEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.uiImageNumberEdit.setReadOnly(True)
        self.uiImageNumberEdit.setObjectName("uiImageNumberEdit")
        self.horizontalLayout_7.addWidget(self.uiImageNumberEdit)
        self.uiPrevImageBtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.uiPrevImageBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiPrevImageBtn.sizePolicy().hasHeightForWidth())
        self.uiPrevImageBtn.setSizePolicy(sizePolicy)
        self.uiPrevImageBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/plugins/APIS/icons/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiPrevImageBtn.setIcon(icon6)
        self.uiPrevImageBtn.setAutoDefault(False)
        self.uiPrevImageBtn.setObjectName("uiPrevImageBtn")
        self.horizontalLayout_7.addWidget(self.uiPrevImageBtn)
        self.uiNextImageBtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.uiNextImageBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiNextImageBtn.sizePolicy().hasHeightForWidth())
        self.uiNextImageBtn.setSizePolicy(sizePolicy)
        self.uiNextImageBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/plugins/APIS/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiNextImageBtn.setIcon(icon7)
        self.uiNextImageBtn.setAutoDefault(False)
        self.uiNextImageBtn.setObjectName("uiNextImageBtn")
        self.horizontalLayout_7.addWidget(self.uiNextImageBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.uiPropertyPlaceholderLbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.uiPropertyPlaceholderLbl.setAutoFillBackground(False)
        self.uiPropertyPlaceholderLbl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.uiPropertyPlaceholderLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.uiPropertyPlaceholderLbl.setObjectName("uiPropertyPlaceholderLbl")
        self.gridLayout_2.addWidget(self.uiPropertyPlaceholderLbl, 0, 0, 1, 1)
        self.uiImageView = QtWidgets.QGraphicsView(self.gridLayoutWidget_2)
        self.uiImageView.setObjectName("uiImageView")
        self.gridLayout_2.addWidget(self.uiImageView, 2, 0, 1, 1)
        self.uiImagePropertiesTab = QtWidgets.QTabWidget(self.gridLayoutWidget_2)
        self.uiImagePropertiesTab.setObjectName("uiImagePropertiesTab")
        self.tabProperties = QtWidgets.QWidget()
        self.tabProperties.setObjectName("tabProperties")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabProperties)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.uiRemoveProjectObliqueBtn = QtWidgets.QPushButton(self.tabProperties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiRemoveProjectObliqueBtn.sizePolicy().hasHeightForWidth())
        self.uiRemoveProjectObliqueBtn.setSizePolicy(sizePolicy)
        self.uiRemoveProjectObliqueBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/plugins/APIS/icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiRemoveProjectObliqueBtn.setIcon(icon8)
        self.uiRemoveProjectObliqueBtn.setAutoDefault(False)
        self.uiRemoveProjectObliqueBtn.setObjectName("uiRemoveProjectObliqueBtn")
        self.gridLayout_4.addWidget(self.uiRemoveProjectObliqueBtn, 3, 3, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.uiSavePropertiesBtn = QtWidgets.QPushButton(self.tabProperties)
        self.uiSavePropertiesBtn.setAutoDefault(False)
        self.uiSavePropertiesBtn.setObjectName("uiSavePropertiesBtn")
        self.horizontalLayout_4.addWidget(self.uiSavePropertiesBtn)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 5, 0, 1, 4)
        self.uiAddProjectObliqueBtn = QtWidgets.QPushButton(self.tabProperties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiAddProjectObliqueBtn.sizePolicy().hasHeightForWidth())
        self.uiAddProjectObliqueBtn.setSizePolicy(sizePolicy)
        self.uiAddProjectObliqueBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/plugins/APIS/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiAddProjectObliqueBtn.setIcon(icon9)
        self.uiAddProjectObliqueBtn.setAutoDefault(False)
        self.uiAddProjectObliqueBtn.setObjectName("uiAddProjectObliqueBtn")
        self.gridLayout_4.addWidget(self.uiAddProjectObliqueBtn, 2, 3, 1, 1)
        self.uiProjectObliqueCombo = QtWidgets.QComboBox(self.tabProperties)
        self.uiProjectObliqueCombo.setObjectName("uiProjectObliqueCombo")
        self.gridLayout_4.addWidget(self.uiProjectObliqueCombo, 1, 1, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.tabProperties)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 0, 1, 1)
        self.uiEditProjectTableObliqueBtn = QtWidgets.QPushButton(self.tabProperties)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiEditProjectTableObliqueBtn.sizePolicy().hasHeightForWidth())
        self.uiEditProjectTableObliqueBtn.setSizePolicy(sizePolicy)
        self.uiEditProjectTableObliqueBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/plugins/APIS/icons/sketch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiEditProjectTableObliqueBtn.setIcon(icon10)
        self.uiEditProjectTableObliqueBtn.setAutoDefault(False)
        self.uiEditProjectTableObliqueBtn.setObjectName("uiEditProjectTableObliqueBtn")
        self.gridLayout_4.addWidget(self.uiEditProjectTableObliqueBtn, 1, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tabProperties)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.uiProjectObliqueList = QtWidgets.QListWidget(self.tabProperties)
        self.uiProjectObliqueList.setObjectName("uiProjectObliqueList")
        self.gridLayout_4.addWidget(self.uiProjectObliqueList, 2, 0, 3, 3)
        self.uiImageDescriptionEdit = QtWidgets.QLineEdit(self.tabProperties)
        self.uiImageDescriptionEdit.setObjectName("uiImageDescriptionEdit")
        self.gridLayout_4.addWidget(self.uiImageDescriptionEdit, 0, 1, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.uiImagePropertiesTab.addTab(self.tabProperties, "")
        self.tabTargets = QtWidgets.QWidget()
        self.tabTargets.setObjectName("tabTargets")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabTargets)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.tabTargets)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.uiTargetsTableV = QtWidgets.QTableView(self.tabTargets)
        self.uiTargetsTableV.setStyleSheet("selection-background-color: rgb(152, 202, 255);\n"
"selection-color: rgb(0, 0, 0);")
        self.uiTargetsTableV.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.uiTargetsTableV.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.uiTargetsTableV.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.uiTargetsTableV.setObjectName("uiTargetsTableV")
        self.verticalLayout_4.addWidget(self.uiTargetsTableV)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.uiSaveTargetsBtn = QtWidgets.QPushButton(self.tabTargets)
        self.uiSaveTargetsBtn.setAutoDefault(False)
        self.uiSaveTargetsBtn.setObjectName("uiSaveTargetsBtn")
        self.horizontalLayout_6.addWidget(self.uiSaveTargetsBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.uiImagePropertiesTab.addTab(self.tabTargets, "")
        self.tabImagesAndLocation = QtWidgets.QWidget()
        self.tabImagesAndLocation.setObjectName("tabImagesAndLocation")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabImagesAndLocation)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.uiImageMapCanvas = QgsMapCanvas(self.tabImagesAndLocation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiImageMapCanvas.sizePolicy().hasHeightForWidth())
        self.uiImageMapCanvas.setSizePolicy(sizePolicy)
        self.uiImageMapCanvas.setObjectName("uiImageMapCanvas")
        self.verticalLayout_5.addWidget(self.uiImageMapCanvas)
        self.uiImagePropertiesTab.addTab(self.tabImagesAndLocation, "")
        self.gridLayout_2.addWidget(self.uiImagePropertiesTab, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.uiTablePropertiesSplitter)

        self.retranslateUi(apisImageSelectionListDialog)
        self.uiImagePropertiesTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(apisImageSelectionListDialog)

    def retranslateUi(self, apisImageSelectionListDialog):
        _translate = QtCore.QCoreApplication.translate
        apisImageSelectionListDialog.setWindowTitle(_translate("apisImageSelectionListDialog", "APIS Bild Auswahl"))
        self.uiResetSelectionBtn.setToolTip(_translate("apisImageSelectionListDialog", "Selektion zurücksetzen"))
        self.uiImageTBtn.setText(_translate("apisImageSelectionListDialog", "Bilder ..."))
        self.uiLayerTBtn.setText(_translate("apisImageSelectionListDialog", "Layer ..."))
        self.uiPdfExportTBtn.setText(_translate("apisImageSelectionListDialog", "PDF Export ..."))
        self.uiTogglePropertyPanelBtn.setText(_translate("apisImageSelectionListDialog", "Properties <<"))
        self.label.setText(_translate("apisImageSelectionListDialog", "Kartiert:"))
        self.uiImageCountLbl.setText(_translate("apisImageSelectionListDialog", "0"))
        self.label_5.setText(_translate("apisImageSelectionListDialog", "/"))
        self.uiImageFilterCountLbl.setText(_translate("apisImageSelectionListDialog", "-"))
        self.label_6.setText(_translate("apisImageSelectionListDialog", "/"))
        self.uiImageSelectedCountLbl.setText(_translate("apisImageSelectionListDialog", "0"))
        self.label_2.setText(_translate("apisImageSelectionListDialog", "Scan:"))
        self.uiScanCountLbl.setText(_translate("apisImageSelectionListDialog", "0"))
        self.label_7.setText(_translate("apisImageSelectionListDialog", "/"))
        self.uiScanFilterCountLbl.setText(_translate("apisImageSelectionListDialog", "-"))
        self.label_8.setText(_translate("apisImageSelectionListDialog", "/"))
        self.uiScanSelectedCountLbl.setText(_translate("apisImageSelectionListDialog", "0"))
        self.label_3.setText(_translate("apisImageSelectionListDialog", "HiRes:"))
        self.uiHiResCountLbl.setText(_translate("apisImageSelectionListDialog", "0"))
        self.label_10.setText(_translate("apisImageSelectionListDialog", "/"))
        self.uiHiResFilterCountLbl.setText(_translate("apisImageSelectionListDialog", "-"))
        self.label_11.setText(_translate("apisImageSelectionListDialog", "/"))
        self.uiHiResSelectedCountLbl.setText(_translate("apisImageSelectionListDialog", "0"))
        self.label_4.setText(_translate("apisImageSelectionListDialog", "Ortho:"))
        self.uiOrthoCountLbl.setText(_translate("apisImageSelectionListDialog", "0"))
        self.label_13.setText(_translate("apisImageSelectionListDialog", "/"))
        self.uiOrthoFilterCountLbl.setText(_translate("apisImageSelectionListDialog", "-"))
        self.label_14.setText(_translate("apisImageSelectionListDialog", "/"))
        self.uiOrthoSelectedCountLbl.setText(_translate("apisImageSelectionListDialog", "0"))
        self.uiImageCountLabelLbl.setText(_translate("apisImageSelectionListDialog", "Gesamt / Filter / Selektiert"))
        self.uiFilterGrp.setTitle(_translate("apisImageSelectionListDialog", "Filter"))
        self.uiFilterVerticalChk.setText(_translate("apisImageSelectionListDialog", "senkrecht"))
        self.uiFilterScaleOperatorCombo.setItemText(0, _translate("apisImageSelectionListDialog", ">="))
        self.uiFilterScaleOperatorCombo.setItemText(1, _translate("apisImageSelectionListDialog", "="))
        self.uiFilterScaleOperatorCombo.setItemText(2, _translate("apisImageSelectionListDialog", "<="))
        self.uiFilterObliqueChk.setText(_translate("apisImageSelectionListDialog", "schräg"))
        self.uiFilterScaleLbl.setText(_translate("apisImageSelectionListDialog", "Maßstab/Radius"))
        self.uiFilterScanCombo.setItemText(0, _translate("apisImageSelectionListDialog", "ja"))
        self.uiFilterScanCombo.setItemText(1, _translate("apisImageSelectionListDialog", "nein"))
        self.uiFilterScanChk.setText(_translate("apisImageSelectionListDialog", "Scan"))
        self.uiFilterOrthoCombo.setItemText(0, _translate("apisImageSelectionListDialog", "ja"))
        self.uiFilterOrthoCombo.setItemText(1, _translate("apisImageSelectionListDialog", "nein"))
        self.uiFilterOrthoChk.setText(_translate("apisImageSelectionListDialog", "Ortho"))
        self.uiFilterHiResCombo.setItemText(0, _translate("apisImageSelectionListDialog", "ja"))
        self.uiFilterHiResCombo.setItemText(1, _translate("apisImageSelectionListDialog", "nein"))
        self.uiFilterFilmKindChk.setText(_translate("apisImageSelectionListDialog", "Filmart"))
        self.uiFilterHiResChk.setText(_translate("apisImageSelectionListDialog", "HiRes"))
        self.uiFilterToDate.setDisplayFormat(_translate("apisImageSelectionListDialog", "yyyy"))
        self.uiFilterFromDate.setDisplayFormat(_translate("apisImageSelectionListDialog", "yyyy"))
        self.uiFilterFromChk.setText(_translate("apisImageSelectionListDialog", "Jahr ab:"))
        self.uiFilterToChk.setText(_translate("apisImageSelectionListDialog", "Jahr bis:"))
        self.uiImageNumberEdit.setPlaceholderText(_translate("apisImageSelectionListDialog", "Bildnummer"))
        self.uiPropertyPlaceholderLbl.setText(_translate("apisImageSelectionListDialog", "Selektieren Sie eines oder mehrere Bilder."))
        self.uiSavePropertiesBtn.setText(_translate("apisImageSelectionListDialog", "Speichern"))
        self.label_17.setText(_translate("apisImageSelectionListDialog", "Projekt(e):"))
        self.label_15.setText(_translate("apisImageSelectionListDialog", "Beschreibung:"))
        self.uiImagePropertiesTab.setTabText(self.uiImagePropertiesTab.indexOf(self.tabProperties), _translate("apisImageSelectionListDialog", "Eigenschaften"))
        self.label_9.setText(_translate("apisImageSelectionListDialog", "Warnung"))
        self.uiSaveTargetsBtn.setText(_translate("apisImageSelectionListDialog", "Speichern"))
        self.uiImagePropertiesTab.setTabText(self.uiImagePropertiesTab.indexOf(self.tabTargets), _translate("apisImageSelectionListDialog", "Targets"))
        self.uiImagePropertiesTab.setTabText(self.uiImagePropertiesTab.indexOf(self.tabImagesAndLocation), _translate("apisImageSelectionListDialog", "Lage"))

from qgis.gui import QgsMapCanvas
import resource_rc
